### PR TITLE
Css vaults

### PR DESCRIPTION
**Pull request by lanejohns**
Please review our code and let me know if we need to make any changes.

Jevon and I mainly worked on the feature to add a movie to a vault, and then the ability to see the movies in the respective vault. I also did some light touch on styling to match everyone else's design.

### CODE REVIEW

**Review by edherm — CHANGES_REQUESTED** [review]
There are a few things for y'all to review below. Let me know when you're good for me to come back to this, though I probably won't be able to get back to it before class tomorrow.

In public/javascripts/movie.js, please remove all of the trailing line breaks before the closing brackets.

Please remove lines 28, 24, and 23 from routes/movies.js for readability and to keep your styling in line with the rest of your routes.

In routes/vaults, the comments should be cleaned up so there's only one ore two lines per block of code.

Optional: Eventually, y'all should create a mixin for form inputs and refactor all of your forms to use it. It is the same lines of code over and over again and you can really dry up pug forms with this. If there are other priorities, please open an issue on your repo and add it to your project/kanban board so that y'all can do this. It just looks so slick (which is ironic, because the code is so DRY). You could start this with the form in this PR (movie.pug).

**Comment by guipace** [comment]
Lane, Jevon, I created a mixen for form inputs, following Ed's suggestion on my pull request. You may be able to use that, although I'm not sure how universal the format I created is. I used it on the login and signup pages.

**Comment by lanejohns** [comment]
Hi Ed, we have made the changes to clean up our code. I think we will hold off on the additional mixins until we complete the last required features for the app!

**Review by edherm — APPROVED** [review]
Thanks for these changes, y'all!

**Pull request merged**
